networks:
  frontend:
    name: frontend

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    privileged: true
    volumes:
      - './data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - '8000:8000' # Portainer Agent
      - '9443:9443' # HTTPS
      - '9000:9000' # HTTP